package com.test2.db.test2_db.entity.base;

/**
 * 
 * 
  _____                      _              _ _ _     _   _     _        __ _ _      
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |     
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___ 
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|
 
                                                                                   
 * DO NOT EDIT THIS FILE!! 
 *
 *  FOR CUSTOMIZE AssetBase PLEASE EDIT ../Asset.java
 * 
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER CODE GENERATION --
 * 
 */
 

/**
 * This is the model of Asset object
 * 
 */
 
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.math.BigDecimal;


import org.springframework.jdbc.core.RowMapper;
import com.test2.db.test2_db.entity.Asset;

public class AssetBase implements RowMapper<Asset>{
	
	private Long _id;
	
	// Attributes
    private String nane;
	
	// Relations fk_asset_user
	private String fk_asset_user;
	
	
	
	@Override
	public Asset mapRow(ResultSet rs, int rowNum) throws SQLException {
		
		Asset obj = new Asset();
		try {
			obj.set_id(rs.getLong("id"));
			obj.setNane(rs.getString("nane"));
			
        	
        	// Relations 1:m fk_asset_user
			obj.setFk_asset_user(rs.getString("fk_asset_user"));
        	
		}
		catch(Exception e) {
			e.printStackTrace();
		}
		return obj;
	}


	public Long get_id() {
		return _id;
	}

	public void set_id(Long _id) {
		this._id = _id;
	}
	
	public String getNane() {
		return nane;
	}


	public void setNane(String nane) {
		this.nane = nane;
	}
	
    
    // Relations 1:m fk_asset_user
	public String getFk_asset_user() {
		return fk_asset_user;
	}

	public void setFk_asset_user(String fk_asset_user) {
		this.fk_asset_user = fk_asset_user;
	}
    
    
    
    
}